# Generated by Django 3.1.3 on 2021-04-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0003_auto_20210428_2234'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_no', models.IntegerField(default=1)),
                ('course', models.ManyToManyField(to='course.Course')),
                ('subject', models.ManyToManyField(to='subject.Subject')),
            ],
        ),
    ]
