# Generated by Django 3.1.3 on 2021-04-30 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sem', '0002_sem_semname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sem',
            name='semname',
        ),
    ]
