# Generated by Django 3.1.5 on 2021-01-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
