# Generated by Django 3.0.8 on 2020-07-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BCA', 'BCA'), ('BBA_IT', 'BBA_IT'), ('BSCIT', 'BSCIT')], max_length=255)),
            ],
        ),
    ]
