# Generated by Django 3.1.3 on 2021-04-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='no_of_students',
            field=models.IntegerField(default=0),
        ),
    ]
