# Generated by Django 3.1.3 on 2021-04-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_no_of_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='no_of_students',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
