# Generated by Django 3.1.3 on 2021-04-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210428_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='BCA', max_length=255),
        ),
    ]
