# Generated by Django 3.0.8 on 2020-07-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='answer_marks',
        ),
        migrations.AddField(
            model_name='grade',
            name='question_marks',
            field=models.IntegerField(default=10),
        ),
    ]
