# Generated by Django 3.0.8 on 2020-07-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20200717_1637'),
        ('grades', '0003_auto_20200717_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='assignment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment'),
        ),
    ]
