# Generated by Django 3.0.8 on 2020-07-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_grade_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='question_marks',
            field=models.IntegerField(default=10),
        ),
    ]
