# Generated by Django 3.2 on 2021-05-07 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import notes.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0002_teacher_qualification'),
        ('subject', '0002_auto_20210429_1936'),
        ('course', '0004_auto_20210429_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Content Here')),
                ('attachement', models.FileField(upload_to='notes', validators=[notes.validators.validate_file_extension])),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
    ]
