# Generated by Django 3.0.8 on 2020-10-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pdf',
            field=models.FileField(default='sample.pdf', upload_to='answers'),
        ),
    ]
