# Generated by Django 3.1.5 on 2021-01-20 10:49

import answer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_auto_20201006_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pdf',
            field=models.FileField(default='sample.pdf', upload_to='answers', validators=[answer.validators.validate_file_extension]),
        ),
    ]
