# Generated by Django 3.1.5 on 2021-01-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_auto_20210120_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='marks',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
