# Generated by Django 3.1.5 on 2021-01-23 10:53

import answer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0004_answer_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pdf',
            field=models.FileField(upload_to='answers', validators=[answer.validators.validate_file_extension]),
        ),
    ]
