# Generated by Django 3.1.4 on 2021-01-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assignment_accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
    ]
