# Generated by Django 3.1.5 on 2021-01-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('student', '0003_student_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='assigned_subject',
        ),
        migrations.AddField(
            model_name='student',
            name='assigned_subject',
            field=models.ManyToManyField(to='subject.Subject'),
        ),
    ]
