# Generated by Django 3.1.7 on 2021-04-20 18:38

from django.db import migrations, models
import student.validators


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210128_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='student_profile_pics', validators=[student.validators.validate_file_extension]),
        ),
    ]
