# Generated by Django 3.1.3 on 2021-04-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sem', '0003_remove_sem_semname'),
        ('student', '0005_auto_20210421_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.ManyToManyField(to='sem.Sem'),
        ),
    ]
