# Generated by Django 3.1.3 on 2021-04-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sem',
        ),
    ]
