# Generated by Django 3.1.3 on 2021-04-30 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sem', '0003_remove_sem_semname'),
        ('student', '0007_remove_student_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='sem.sem'),
            preserve_default=False,
        ),
    ]
