# Generated by Django 3.0.8 on 2020-07-17 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 10, 55, 23, 370524, tzinfo=utc)),
        ),
    ]
