# Generated by Django 3.0.8 on 2020-07-17 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20200717_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 10, 56, 35, 588720, tzinfo=utc)),
        ),
    ]
