# Generated by Django 3.1.5 on 2021-01-23 10:52

import assignment.validators
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_auto_20210114_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 24, 10, 52, 56, 759769, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='pdf',
            field=models.FileField(upload_to='assignments', validators=[assignment.validators.validate_file_extension]),
        ),
    ]
