# Generated by Django 3.1.7 on 2021-04-10 07:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_auto_20210327_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='views',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 7, 57, 37, 673509, tzinfo=utc)),
        ),
    ]
