# Generated by Django 3.1.3 on 2021-04-28 13:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0011_auto_20210415_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 13, 27, 38, 785198, tzinfo=utc)),
        ),
    ]
