# Generated by Django 3.1.3 on 2021-04-28 17:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0012_auto_20210428_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 17, 4, 40, 649436, tzinfo=utc)),
        ),
    ]
