# Generated by Django 3.1.3 on 2021-04-30 04:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0013_auto_20210428_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 4, 45, 10, 634994, tzinfo=utc)),
        ),
    ]
