# Generated by Django 3.1.3 on 2021-04-30 05:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0014_auto_20210430_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 5, 14, 47, 623278, tzinfo=utc)),
        ),
    ]
