# Generated by Django 3.2 on 2021-05-01 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0016_auto_20210430_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 14, 43, 56, 482382, tzinfo=utc)),
        ),
    ]
